# Generated by Django 4.2.14 on 2025-02-06 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_alter_user_groups_alter_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('ROLE_ASSIGNMENT', 'Role Assignment'), ('PROFILE_UPDATE', 'Profile Update'), ('INTERACTION', 'Interaction'), ('NOTE', 'Note'), ('GROUP_CREATION', 'Group Creation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
